# Site settings
title: Analytics Project
description: The webpage for Analytics Projects course at the SIMT ITS
baseurl: ""
url: "https://analyticsprojects.id"

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from

# Redirect settings
redirect_from:
  json: false

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - .sass-cache

# Firebase configuration
firebase:
  api_key: "AIzaSyDs6aQSk9c6cSDvFINlwy2DJ0uqtTAds1g"
  auth_domain: "sync-slide-40285.firebaseapp.com"
  database_url: "https://sync-slide-40285-default-rtdb.asia-southeast1.firebasedatabase.app"
  project_id: "sync-slide-40285"
  storage_bucket: "sync-slide-40285.firebasestorage.app"
  messaging_sender_id: "878059923546"
  app_id: "1:878059923546:web:2dcf4e13ef7a8913735063"
  measurement_id: "G-J1D5F11B8T"

