# Site settings
title: Analytics Project
description: The webpage for Analytics Projects course at the SIMT ITS
baseurl: ""
url: "https://analytics-project-simt-its.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from

# Redirect settings
redirect_from:
  json: false

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore

