# Site settings
title: Analytics Project
description: The webpage for Analytics Projects course at the SIMT ITS
baseurl: ""
url: "https://analyticsprojects.id"

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from

# Redirect settings
redirect_from:
  json: false

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - .sass-cache

# Firebase configuration
firebase:
  api_key: ${{ secrets.FIREBASE_API_KEY }}
  auth_domain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  database_url: ${{ secrets.FIREBASE_DATABASE_URL }}
  project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
  storage_bucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  messaging_sender_id: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  app_id: ${{ secrets.FIREBASE_APP_ID }}
  measurement_id: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

