name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Append firebase config into _config.yml
        run: |
          echo "firebase:" >> _config.yml
          echo "  api_key: ${{ vars.FIREBASE_API_KEY }}" >> _config.yml
          echo "  auth_domain: ${{ vars.FIREBASE_AUTH_DOMAIN }}" >> _config.yml
          echo "  database_url: ${{ vars.FIREBASE_DATABASE_URL }}" >> _config.yml
          echo "  project_id: ${{ vars.FIREBASE_PROJECT_ID }}" >> _config.yml
          echo "  storage_bucket: ${{ vars.FIREBASE_STORAGE_BUCKET }}" >> _config.yml
          echo "  messaging_sender_id: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" >> _config.yml
          echo "  app_id: ${{ vars.FIREBASE_APP_ID }}" >> _config.yml
          echo "  measurement_id: ${{ vars.FIREBASE_MEASUREMENT_ID }}" >> _config.yml

      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
        env:
          FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ vars.FIREBASE_MEASUREMENT_ID }}


